name: Divar Scraper
on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:  

jobs:
  scrape:
    runs-on: ubuntu-latest
    permissions:  
        contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
            token: ${{ secrets.GHUB_TOKEN }} 
            fetch-depth: 0 
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver

      - name: Run Scraper
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          DIVARURL: ${{ secrets.DIVARURL }}
        run: python main.py

      - name: Commit changes
        run: |
            git config --global user.name "GitHub Actions"
            git config --global user.email "actions@github.com"
            git remote set-url origin https://x-access-token:${{ secrets.GHUB_TOKEN }}@github.com/${{ github.repository }}
            if [ -f ads_history.json ]; then
                git add ads_history.json
                git commit -m "Update ads history" || echo "No changes to commit"
                git pull origin main --rebase
                git push origin main
            else
                echo "ads_history.json not found!"
            fi